#!/usr/bin/env bash
set -eu -o pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

declare -r ERR_ROOT=32

main() {
	if (( ${UID} == 0 )); then
		printf "script must be not be run as root.\n"
		return "${ERR_ROOT}"
	fi

	install_packages
}

install_packages() {
  for package_dir in ./packages/*; do
    local package_installer="$package_dir/install-interactive"

    if [[ -x "$package_installer" ]]; then
      install_package "$package_installer"
    fi
  done
}

install_package() {
  local package_installer="$1"
  echo "Installing package with installer '$package_installer'"
  "$package_installer"
}

main "${@}"
