#!/usr/bin/env bash
set -eu -o pipefail
cd "$(dirname "${BASH_SOURCE[${#BASH_SOURCE[@]} - 1]}")"

source ./include/utils

main() {
	ensure_not_root
	install_base
	install_packages
}

install_base() {
	sudo ./base/install
	./base/config
}

install_packages() {
	for package_dir in ./packages/*; do
		local package_installer="$package_dir/install"

		if [[ -x "$package_installer" ]]; then
			install_package "$package_installer"
		fi
	done
}

install_package() {
	local package_installer="$1"
	echo "Installing package with installer '$package_installer'"
	"$package_installer"
}

main
