#!/usr/bin/env bash
set -eu -o pipefail
cd "$(dirname "${BASH_SOURCE[${#BASH_SOURCE[@]} - 1]}")"

source ../include/utils

main() {
  info

  ensure_root
  install_base
}

install_base() {
  install_packages stow htop tree tcpdump iotop iftop awscli tmux gnupg2
  install_packages libtool autoconf automake cmake gcc g++ make pkg-config unzip
  install_packages sl
}

main
