#!/usr/bin/env bash
set -eu -o pipefail
cd "$(dirname "${BASH_SOURCE[${#BASH_SOURCE[@]} - 1]}")"

source ../include/utils

main() {
  info

  ensure_root
  install_base
}

install_base() {
  install_packages epel-release
  install_packages stow htop tree tcpdump iftop awscli tmux gpg
  install_packages libtool autoconf automake cmake gcc gcc-c++ make pkgconfig unzip
  install_packages sl
}

main
